name: Update Auction Data

on:
  schedule:
    # 평일(월~금): 한국시간 20-22시 매 10분마다 (UTC 11-13시)
    - cron: "0,10,20,30,40,50 11,12,13 * * 1-5"
    # 주말(토~일): 한국시간 4시간마다 (0,4,8,12,16,20시 = UTC 15,19,23,3,7,11시)
    - cron: "0 15,19,23 * * 6,0"  # 토요일 0,4,8시, 일요일 0,4,8시
    - cron: "0 3,7,11 * * 6,0"    # 토요일 12,16,20시, 일요일 12,16,20시
  workflow_dispatch:       # 수동 실행 버튼

permissions:
  contents: write          # 커밋/푸시 권한

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run downloader
        run: python download_if_changed.py

      - name: Commit changes if any
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "Update auction data [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi